# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Weibo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for Weibo

    pod "Alamofire"  , '~> 4.6.0'
    pod "IQKeyboardManagerSwift"   , '~> 5.0.6'
    pod "Kingfisher"   , '~> 4.5.0'
    pod "SnapKit", '~> 4.0.0'
    pod "YYKit"
    #  pod "Reachability"   , '~> 3.2'
    # SwiftLint autocorrect

    pod "FMDB"

    #####  pod install --verbose --no-repo-update

end
